# Unable to run LeakSanitizer propertly without root
#   https://github.com/travis-ci/travis-ci/issues/9033
sudo: true
language: cpp
notifications:
  email: false

# Use Linux + gcc unless specified
os: linux
dist: xenial
compiler: gcc

env:
  global:
    - LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
    - DEBUG=1

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      travis_wait 30 brew update;
    else
      sudo apt-get update;
    fi
  - |
    if [ -n "${MATRIX_INIT}" ]; then
      eval "${MATRIX_INIT}"
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make -j 4

  - cd ${TRAVIS_BUILD_DIR}
  - make -j 4 test
  - bash <(curl --no-buffer -s https://codecov.io/bash) > codecov_output
  - head -n 100 codecov_output

matrix:
  include:
    - name: "gcc-5"
      env:
        - CC=gcc-5
        - CXX=g++-5
        - OCCA_COVERAGE=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - name: "gcc-6"
      env:
        - CC=gcc-6
        - CXX=g++-6
        - OCCA_COVERAGE=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - name: "gcc-7"
      env:
        - CC=gcc-7
        - CXX=g++-7
        - OCCA_COVERAGE=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - name: "gcc-7 (CMake)"
      env:
        - CC=gcc-7
        - CXX=g++-7
        - OCCA_COVERAGE=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - cmake
          packages:
            - g++-7
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir build
        - cd build
        - cmake ..
        - make -j 4
    - name: "clang-4.0"
      env:
        - CC=clang-4.0
        - CXX=clang++-4.0
        - CODECOV=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-4.0
          packages:
            - clang-4.0
    - name: "clang-5.0"
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0
        - CODpECOV=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-5.0
          packages:
            - clang-5.0
    - name: "clang-6.0"
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
        - CODECOV=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-6.0
          packages:
            - clang-6.0
    - name: "clang"
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
        - CODECOV=OFF
